[misc]
no_self_update = true
only = ["system", "flatpak", "distrobox", "firmware"]
disable = ["self_update", "toolbx", "containers", "helm"]
ignore_failures = ["distrobox", "flatpak", "brew_cask", "brew_formula", "nix", "node", "pip3", "home_manager", "firmware"]
assume_yes = true
no_retry = false

[linux]
rpm_ostree = true
