css: |
  .global-section banner {
     margin-top: 30px;
     margin-left: 30px;
     margin-right: 30px;
     border-radius: 10px;
  }
  .global-section banner-text-overlay {
     margin: 30px;
     padding: 20px;
  }
  .global-section banner-text {
     padding: 50px;
     text-shadow: 1px 1px 4px rgba(0, 0, 5, 1);
  }
  .global-section title {
     text-shadow: 1px 1px 4px rgba(0, 0, 5, 1);
  }
  .global-section subtitle {
    font-weight: 400;
    text-shadow: 4px 4px 8px rgba(0, 0, 5, 1);
  }

  .global-section app-tile > button {
    background-color: alpha(white, 0.1);
  }

  .global-section {
    margin: 15px;
    border-radius: 25px;
    color: #ffffff;
  }

  .rec-section {
    background: linear-gradient(0deg, #774c45, #a5897b);
  }
  .rec-section-dark {
    background: linear-gradient(to top, #0d0e19, #111324, #13182f, #161b3b, #1a1f47, #1e2351, #22275c, #272b66, #2c3171, #31387d, #363e88, #3b4594);
  }

  .browser-section {
    background: linear-gradient(to left top, #252b57, #2b305b, #32365f, #383b63, #3e4167, #43476b, #494c6e, #4e5272, #545877, #5a5f7b, #606580, #666c84);
  }

  .browser-section app-tile > button {
    color: #ffffff;
  }

  .browser-section app-tile-installed-indicator {
    color: #ffffff;
  }

  .browser-section-dark {
    background: linear-gradient(to left top, #1f2843, #252e49, #2c344f, #323a56, #39405c, #414865, #494f6e, #515777, #5d6385, #696f93, #757ba2, #8288b1);
  }

  .music-section {
    background: linear-gradient(0deg, #356c94, #64aec7);
  }
  .music-section-dark {
    background: linear-gradient(to top, #10202c, #122432, #152937, #172d3d, #1a3243, #1f394b, #244053, #29475b, #325368, #3b5f74, #446b81, #4d788e);
  }

  .office-section {
    background: linear-gradient(0deg, #2a2d2c, #b69092);
  }
  .office-section app-tile > button {
    color: #ffffff;
  }
  .office-section app-tile-installed-indicator {
    color: #ffffff;
  }

  .office-section-dark {
    background: linear-gradient(to top, #030a15, #070e19, #0a111d, #0d1421, #0f1625, #131c2f, #17233a, #1c2945, #25365b, #2f4371, #3a5088, #465ea0);
  }

  .gaming-section {
    background: linear-gradient(0deg, #1c3727, #85d0b0);
  }
  .gaming-section app-tile-installed-indicator {
    color: #243a98;
  }

  .gaming-section-dark {
    background: linear-gradient(0deg, #080914, #393a58);
  }

  .utilities-section {
    background: linear-gradient(to left top, #282217, #373227, #474438, #585549, #69685c, #747468, #808175, #8c8e82, #94988c, #9da395, #a5ada0, #adb8aa);
  }
  .utilities-section-dark {
    background: linear-gradient(to left top, #111b24, #15202d, #1a2636, #212b3f, #293048, #313652, #3a3c5c, #444266, #4f4b74, #5a5582, #665e90, #72689f);
  }

  .dev-section {
    background: linear-gradient(90deg, #8c4d38 0%, #906860 55%, #8c4d38 100%);
  }
  .dev-section-dark {
    background: linear-gradient(90deg, #241a23 0%, #75554e 55%, #241a23 100%);
  }

  .edu-section {
    background: linear-gradient(45deg, #2a0e07, #7f4f39);
  }
  .edu-section app-tile > button {
    color: #ffffff;
  }
  .edu-section app-tile-installed-indicator {
    color: #ffffff;
  }

  .edu-section-dark {
    background: linear-gradient(45deg, #2b1c2c, #4C6897);
  }

  .ai-section {
    background: linear-gradient(90deg, #b56537 0%, #ffb267 35%, #b56537 100%);
  }
  .ai-section-dark {
    background: linear-gradient(90deg, #004466 0%, #507aa2 35%, #004466 100%);
  }

sections:
  - title: "Bluefin Recommends"
    subtitle: "Our Favorite Applications"
    rows: 3
    light-banner: file:///run/host/etc/bazaar/11-bluefin-day.jxl
    dark-banner: file:///run/host/etc/bazaar/11-bluefin-night.jxl
    banner-fit: cover
    banner-text-halign: end
    banner-text-valign: start
    banner-height: 400
    classes:
      - global-section
    light-classes:
      - rec-section
    dark-classes:
      - rec-section-dark
    appids:
      - net.codelogistics.letters
      - re.sonny.Eloquent
      - page.codeberg.libre_menu_editor.LibreMenuEditor
      - app.fotema.Fotema
      - be.alexandervanhee.gradia
      - app.drey.Damask
      - io.github.pleromix.IceBox
      - com.github.ADBeveridge.Raider
      - org.gnome.gitlab.YaLTeR.VideoTrimmer
      - org.gnome.gitlab.cheywood.Buffer
      - io.github.kelvinnovais.Kasasa
      - de.schmidhuberj.DieBahn
      - com.github.maoschanz.drawing
      - io.github.swordpuffin.rewaita

  - title: "Browsers"
    subtitle: "Use the web with your favorite browser"
    rows: 2
    light-banner: file:///run/host/etc/bazaar/01-bluefin-day.jxl
    dark-banner: file:///run/host/etc/bazaar/01-bluefin-night.jxl
    banner-fit: cover
    banner-text-halign: start
    banner-text-valign: start
    banner-height: 400
    classes:
      - global-section
    light-classes:
      - browser-section
    dark-classes:
      - browser-section-dark
    appids:
      - org.mozilla.firefox
      - com.brave.Browser
      - com.google.Chrome
      - com.microsoft.Edge
      - com.opera.Opera
      - com.vivaldi.Vivaldi

  - title: "Media"
    subtitle: "The Freedom of Music"
    rows: 2
    light-banner: file:///run/host/etc/bazaar/02-bluefin-day.jxl
    dark-banner: file:///run/host/etc/bazaar/02-bluefin-night.jxl
    banner-fit: cover
    banner-text-halign: end
    banner-text-valign: end
    banner-height: 400
    classes:
      - global-section
    light-classes:
      - music-section
    dark-classes:
      - music-section-dark
    appids:
      - com.spotify.Client
      - app.ytmdesktop.ytmdesktop
      - de.haeckerfelix.Shortwave
      - io.bassi.Amberol
      - org.videolan.VLC
      - com.github.wwmm.easyeffects
      - me.timschneeberger.jdsp4linux
      - com.github.iwalton3.jellyfin-media-player
      - tv.plex.PlexDesktop
      - com.plexamp.Plexamp
      - com.rafaelmardojai.Blanket

  - title: "Office & Productivity"
    subtitle: "Work Smarter"
    rows: 4
    light-banner: file:///run/host/etc/bazaar/03-bluefin-day.jxl
    dark-banner: file:///run/host/etc/bazaar/03-bluefin-night.jxl
    banner-fit: cover
    banner-text-halign: start
    banner-text-valign: end
    banner-height: 400
    classes:
      - global-section
    light-classes:
      - office-section
    dark-classes:
      - office-section-dark
    appids:
      - com.slack.Slack
      - md.obsidian.Obsidian
      - io.gitlab.theevilskeleton.Upscaler
      - io.github.alainm23.planify
      - org.blender.Blender
      - org.onlyoffice.desktopeditors
      - org.libreoffice.LibreOffice
      - org.gimp.GIMP
      - org.kde.krita
      - org.inkscape.Inkscape
      - io.github.nokse22.Exhibit
      - com.logseq.Logseq
      - org.audacityteam.Audacity
      - org.ardour.Ardour
      - org.gnome.Fractal
      - org.gnome.gitlab.YaLTeR.VideoTrimmer

  - title: "Games"
    subtitle: "Protocol Three: Protect the Pilot"
    rows: 3
    light-banner: file:///run/host/etc/bazaar/04-bluefin-day.jxl
    dark-banner: file:///run/host/etc/bazaar/04-bluefin-night.jxl
    banner-fit: cover
    banner-text-halign: start
    banner-text-valign: end
    banner-height: 400
    classes:
      - global-section
    light-classes:
      - gaming-section
    dark-classes:
      - gaming-section-dark
    appids:
      - com.valvesoftware.Steam
      - com.heroicgameslauncher.hgl
      - com.discordapp.Discord
      - net.lutris.Lutris
      - com.vysp3r.ProtonPlus
      - com.dec05eba.gpu_screen_recorder
      - com.github.Matoking.protontricks
      - com.obsproject.Studio
      - com.feaneron.Boatswain
      - com.valvesoftware.SteamLink
      - org.gnome.Mahjongg
      - io.github.fragglet.sdl_sopwith
      - io.github.sepehr_rs.Sudoku
      - org.wesnoth.Wesnoth
      - org.endlessaccess.threadbare

  - title: "Utilities"
    subtitle: "Gear up and kit out"
    rows: 4
    light-banner: file:///run/host/etc/bazaar/05-bluefin-day.jxl
    dark-banner: file:///run/host/etc/bazaar/05-bluefin-night.jxl
    banner-fit: cover
    banner-text-halign: start
    banner-text-valign: end
    banner-height: 400
    classes:
      - global-section
    light-classes:
      - utilities-section
    dark-classes:
      - utilities-section-dark
    appids:
      - app.drey.Warp
      - org.localsend.localsend_app
      - com.github.zocker_160.SyncThingy
      - io.github.nozwock.Packet
      - org.gnome.gitlab.somas.Apostrophe
      - org.cockpit_project.CockpitClient
      - org.gnome.gitlab.cheywood.Pulp
      - io.github.vikdevelop.SaveDesktop
      - org.gnome.World.PikaBackup
      - org.fedoraproject.MediaWriter
      - org.raspberrypi.rpi-imager
      - hu.irl.cameractrls
      - com.belmoussaoui.Decoder
      - io.github.wartybix.Constrict
      - io.gitlab.adhami3310.Converter
      - com.jeffser.Pigment
      - com.github.finefindus.eyedropper
      - io.github.plrigaux.sysd-manager
      - org.mozilla.vpn

  - title: "Developers"
    subtitle: "Unleash the power of Cloud Native"
    rows: 4
    light-banner: file:///run/host/etc/bazaar/06-bluefin-day.jxl
    dark-banner: file:///run/host/etc/bazaar/06-bluefin-night.jxl
    banner-fit: cover
    banner-text-halign: end
    banner-text-valign: start
    banner-height: 400
    classes:
      - global-section
    light-classes:
      - dev-section
    dark-classes:
      - dev-section-dark
    appids:
      - io.podman_desktop.PodmanDesktop
      - org.gnome.Builder
      - com.getpostman.Postman
      - me.iepure.devtoolbox
      - io.kinvolk.Headlamp
      - de.leopoldluley.Clapgrep
      - com.mardojai.ForgeSparks
      - io.dbeaver.DBeaverCommunity
      - cc.arduino.IDE2
      - dev.geopjr.Calligraphy
      - io.github.lo2dev.Echo
      - org.gnome.design.IconLibrary
      - io.github.ronniedroid.concessio
      - io.github.nokse22.asciidraw
      - dev.geopjr.Collision
      - io.github.tobagin.digger
      - app.drey.Elastic
      - io.github.mfat.sshpilot

  - title: "Sustainability & Education"
    subtitle: "Invest in the Future"
    rows: 2
    light-banner: file:///run/host/etc/bazaar/10-bluefin-day.jxl
    dark-banner: file:///run/host/etc/bazaar/10-bluefin-night.jxl
    banner-fit: cover
    banner-text-halign: start
    banner-text-valign: end
    banner-height: 400
    classes:
      - global-section
    light-classes:
      - edu-section
    dark-classes:
      - edu-section-dark
    appids:
      - org.endlessos.Key
      - io.github.david_swift.Flashcards
      - dev.bragefuglseth.Keypunch
      - org.tuxpaint.Tuxpaint
      - im.bernard.Memorado
      - io.github.josephmawa.Egghead
      - page.codeberg.lo_vely.Nucleus
      - org.turbowarp.TurboWarp
      - as.may.moat

  - title: "AI and Machine Learning"
    subtitle: "Explore the best of open source AI"
    rows: 1
    light-banner: file:///run/host/etc/bazaar/08-bluefin-day.jxl
    dark-banner: file:///run/host/etc/bazaar/08-bluefin-night.jxl
    banner-fit: cover
    banner-text-halign: end
    banner-text-valign: end
    banner-height: 400
    classes:
      - global-section
    light-classes:
      - ai-section
    dark-classes:
      - ai-section-dark
    appids:
      - com.jeffser.Alpaca
      - io.github.qwersyk.Newelle
