css: |
  .global-section banner {
     margin-top: 30px;
     margin-left: 30px;
     margin-right: 30px;
     border-radius: 10px;
  }
  .global-section banner-text-overlay {
     margin: 30px;
     padding: 20px;
  }
  .global-section banner-text {
     padding: 50px;
     color: inherit;
     text-shadow: 1px 1px 4px rgba(0, 0, 0, 0.7);
  }
  .global-section title {
     color: inherit;
  }
  .global-section subtitle {
    color: inherit;
    font-weight: 400;
  }
  .global-section {
    margin: 15px;
    border-radius: 25px;
    color: #ffffff
  }

  .bluefin-section {
    background: linear-gradient(0deg, #260e0c, #774c45);
  }
  .browser-section {
    background: linear-gradient(to left top, #252b57, #2b305b, #32365f, #383b63, #3e4167, #43476b, #494c6e, #4e5272, #545877, #5a5f7b, #606580, #666c84);
  }
  .music-section {
    background: linear-gradient(to top, #0e2335, #0f273b, #112b41, #122f47, #13334d, #153751, #163a56, #183e5a, #1b425d, #1d4561, #204964, #234d67);
  }
  .office-section {
    background: linear-gradient(0deg, #2a2d2c, #b69092);
  }
  .gaming-section {
    background: linear-gradient(0deg, #1c3727, #294a37);
  }
  .utilities-section {
    background: linear-gradient(to left top, #111b24, #15202d, #1a2636, #212b3f, #293048, #313652, #3a3c5c, #444266, #4f4b74, #5a5582, #665e90, #72689f);
  }
  .dev-section {
    background: linear-gradient(90deg, #2f2320 0%, #906860 50%, #2f2320 100%);
  }
  .edu-section {
    background: linear-gradient(0deg, #2a0e07, #7f4f39);
  }
  .ai-section {
    background: linear-gradient(90deg, #004466 0%, #507aa2 35%, #004466 100%);
  }
sections:
  - title: "Bluefin Recommends"
    subtitle: "Our Favorite Applications"
    rows: 3
    banner: file:///usr/share/ublue-os/bazaar/11-bluefin.png
    banner-fit: cover
    banner-text-halign: end
    banner-text-valign: start
    banner-height: 400
    classes:
      - global-section
    dark-classes:
      - bluefin-section
    appids:
      - re.sonny.Eloquent
      - page.codeberg.libre_menu_editor.LibreMenuEditor
      - app.fotema.Fotema
      - be.alexandervanhee.gradia
      - app.drey.Damask
      - io.github.pleromix.IceBox
      - com.github.ADBeveridge.Raider
      - org.gnome.gitlab.YaLTeR.VideoTrimmer
      - org.gnome.gitlab.cheywood.Buffer
      - io.github.kelvinnovais.Kasasa
      - de.schmidhuberj.DieBahn
      - com.github.maoschanz.drawing
      - io.github.swordpuffin.rewaita
  - title: "Browsers"
    subtitle: "Use the web with your favorite browser"
    rows: 2
    banner: file:///usr/share/ublue-os/bazaar/01-bluefin.png
    banner-fit: cover
    banner-text-halign: start
    banner-text-valign: start
    banner-height: 400
    classes:
      - global-section
    dark-classes:
      - browser-section
    appids:
      - org.mozilla.firefox
      - com.brave.Browser
      - com.google.Chrome
      - com.microsoft.Edge
      - com.opera.Opera
      - com.vivaldi.Vivaldi
  - title: "Media"
    subtitle: "The Freedom of Music"
    rows: 2
    banner: file:///usr/share/ublue-os/bazaar/02-bluefin.png
    banner-fit: cover
    banner-text-halign: end
    banner-text-valign: end
    banner-height: 400
    classes:
      - global-section
    dark-classes:
      - music-section
    appids:
      - com.spotify.Client
      - app.ytmdesktop.ytmdesktop
      - de.haeckerfelix.Shortwave
      - io.bassi.Amberol
      - org.videolan.VLC
      - com.github.wwmm.easyeffects
      - me.timschneeberger.jdsp4linux
      - com.github.iwalton3.jellyfin-media-player
      - tv.plex.PlexDesktop
      - com.plexamp.Plexamp
      - com.rafaelmardojai.Blanket
  - title: "Office & Productivity"
    subtitle: "Work Smarter"
    rows: 4
    banner: file:///usr/share/ublue-os/bazaar/03-bluefin.png
    banner-fit: cover
    banner-text-halign: end
    banner-text-valign: end
    banner-height: 400
    classes:
      - global-section
    dark-classes:
      - office-section
    appids:
      - com.slack.Slack
      - md.obsidian.Obsidian
      - io.gitlab.theevilskeleton.Upscaler
      - io.github.alainm23.planify
      - org.blender.Blender
      - org.onlyoffice.desktopeditors
      - org.libreoffice.LibreOffice
      - org.gimp.GIMP
      - org.kde.krita
      - org.inkscape.Inkscape
      - io.github.nokse22.Exhibit
      - com.logseq.Logseq
      - org.audacityteam.Audacity
      - org.ardour.Ardour
      - org.gnome.Fractal
      - org.gnome.gitlab.YaLTeR.VideoTrimmer
  - title: "Games"
    subtitle: "Protocol Three: Protect the Pilot"
    rows: 3
    banner: file:///usr/share/ublue-os/bazaar/04-bluefin.png
    banner-fit: cover
    banner-text-halign: start
    banner-text-valign: end
    banner-height: 400
    classes:
      - global-section
    dark-classes:
      - gaming-section
    appids:
      - com.valvesoftware.Steam
      - com.heroicgameslauncher.hgl
      - com.discordapp.Discord
      - net.lutris.Lutris
      - com.vysp3r.ProtonPlus
      - com.dec05eba.gpu_screen_recorder
      - com.github.Matoking.protontricks
      - com.obsproject.Studio
      - com.feaneron.Boatswain
      - com.valvesoftware.SteamLink
      - org.gnome.Mahjongg
      - io.github.fragglet.sdl_sopwith
      - io.github.sepehr_rs.Sudoku
      - org.wesnoth.Wesnoth
  - title: "Utilities"
    subtitle: "Gear up and kit out"
    rows: 4
    banner: file:///usr/share/ublue-os/bazaar/05-bluefin.png
    banner-fit: cover
    banner-text-halign: start
    banner-text-valign: end
    banner-height: 400
    classes:
      - global-section
    dark-classes:
      - utilities-section
    appids:
      - app.drey.Warp
      - org.localsend.localsend_app
      - com.github.zocker_160.SyncThingy
      - io.github.nozwock.Packet
      - org.gnome.gitlab.somas.Apostrophe
      - org.cockpit_project.CockpitClient
      - org.gnome.gitlab.cheywood.Pulp
      - io.github.vikdevelop.SaveDesktop
      - org.gnome.World.PikaBackup
      - org.fedoraproject.MediaWriter
      - org.raspberrypi.rpi-imager
      - hu.irl.cameractrls
      - com.belmoussaoui.Decoder
      - io.github.wartybix.Constrict
      - io.gitlab.adhami3310.Converter
      - com.jeffser.Pigment
      - com.github.finefindus.eyedropper
      - io.github.plrigaux.sysd-manager
      - org.mozilla.vpn
  - title: "Developers"
    subtitle: "Unleash the power of Cloud Native"
    rows: 4
    banner: file:///usr/share/ublue-os/bazaar/06-bluefin.png
    banner-fit: cover
    banner-text-halign: end
    banner-text-valign: start
    banner-height: 400
    classes:
      - global-section
    dark-classes:
      - dev-section
    appids:
      - io.podman_desktop.PodmanDesktop
      - org.gnome.Builder
      - com.getpostman.Postman
      - me.iepure.devtoolbox
      - io.kinvolk.Headlamp
      - de.leopoldluley.Clapgrep
      - com.mardojai.ForgeSparks
      - io.dbeaver.DBeaverCommunity
      - cc.arduino.IDE2
      - sh.loft.devpod
      - dev.geopjr.Calligraphy
      - io.github.lo2dev.Echo
      - org.gnome.design.IconLibrary
      - io.github.ronniedroid.concessio
      - io.github.nokse22.asciidraw
      - dev.geopjr.Collision
      - io.github.tobagin.digger
      - app.drey.Elastic
  - title: "Sustainability & Education"
    subtitle: "Invest in the Future"
    rows: 2
    banner: file:///usr/share/ublue-os/bazaar/10-bluefin.png
    banner-fit: cover
    banner-text-halign: start
    banner-text-valign: end
    banner-height: 400
    classes:
      - global-section
    dark-classes:
      - edu-section
    appids:
      - org.endlessos.Key
      - io.github.david_swift.Flashcards
      - dev.bragefuglseth.Keypunch
      - org.tuxpaint.Tuxpaint
      - im.bernard.Memorado
      - io.github.josephmawa.Egghead
      - page.codeberg.lo_vely.Nucleus
      - org.turbowarp.TurboWarp
  - title: "AI and Machine Learning"
    subtitle: "Explore the best of open source AI"
    rows: 1
    banner: file:///usr/share/ublue-os/bazaar/08-bluefin.png
    banner-fit: cover
    banner-text-halign: end
    banner-text-valign: end
    banner-height: 400
    classes:
      - global-section
    dark-classes:
      - ai-section
    appids:
      - com.jeffser.Alpaca
      - io.github.qwersyk.Newelle
