css: |
  .bazzite-section {
     margin: 20px;
     border-radius: 10px;
     background: linear-gradient(to right, alpha(var(--accent-color), 0.2), alpha(var(--accent-bg-color), 0.3));
  }
  .bazzite-section banner {
     margin-top: 20px;
     margin-left: 20px;
     margin-right: 20px;
     border-radius: 10px;
  }
  .bazzite-section banner-text-overlay {
     margin: 30px;
     padding: 20px;
  }
  .bazzite-section banner-text {
     padding: 50px;
     color: lighter(var(--accent-color));
  }
  .bazzite-section title {
     color: #ffffff;
  }
  .bazzite-section subtitle {
     color: #ffffff;
     font-weight: 400;
  }
  .bazzite-section entry {
     background: linear-gradient(to right, alpha(var(--accent-color), 0.2), alpha(var(--accent-bg-color), 0.1));
     transition-property: background;
     transition-duration: 0.25s;
  }
  .bazzite-section entry:hover {
     background: linear-gradient(to right, alpha(var(--accent-bg-color), 0.3), alpha(var(--accent-color), 0.4));
     transition-property: background;
     transition-duration: 0.75s;
  }
  .bazzite-section entry:active {
     background: linear-gradient(to right, alpha(var(--accent-bg-color), 0.6), alpha(var(--accent-color), 0.5));
     transition-property: background;
     transition-duration: 0.15s;
  }
sections:
  - title: "Bluefin Recommends"
    subtitle: "Our Favorite Applications"
    rows: 3
    banner: file:///usr/share/ublue-os/bazaar/streaming.png
    banner-fit: cover
    banner-text-halign: end
    banner-text-valign: start
    banner-height: 500
    classes:
      - bazzite-section
    appids:
      - re.sonny.Eloquent
      - io.github.fabrialberio.pinapp
      - app.fotema.Fotema
      - be.alexandervanhee.gradia
      - app.drey.Damask
      - io.github.pleromix.IceBox
      - com.github.ADBeveridge.Raider
      - org.gnome.gitlab.YaLTeR.VideoTrimmer
      - org.gnome.gitlab.cheywood.Buffer
      - io.github.kelvinnovais.Kasasa
      - de.schmidhuberj.DieBahn
      - com.github.maoschanz.drawing
  - title: "Browsers"
    subtitle: "Use the web with your favorite browser"
    rows: 2
    banner: file:///usr/share/ublue-os/bazaar/gaming.png
    banner-fit: cover
    banner-text-halign: start
    banner-text-valign: start
    banner-height: 500
    classes:
      - bazzite-section
    appids:
      - org.mozilla.firefox
      - com.brave.Browser
      - com.google.Chrome
      - com.microsoft.Edge
      - com.opera.Opera
      - com.vivaldi.Vivaldi
  - title: "Music & Media"
    subtitle: "Let me break it down for you"
    rows: 2
    banner: file:///usr/share/ublue-os/bazaar/music.png
    banner-fit: cover
    banner-text-halign: start
    banner-text-valign: end
    banner-height: 500
    classes:
      - bazzite-section
    appids:
      - com.spotify.Client
      - de.haeckerfelix.Shortwave
      - io.bassi.Amberol
      - org.videolan.VLC
      - com.github.iwalton3.jellyfin-media-player
      - tv.plex.PlexDesktop
      - com.plexamp.Plexamp
      - com.rafaelmardojai.Blanket
  - title: "Office & Productivity"
    subtitle: "May the paperclip be ever in your favor"
    rows: 3
    banner: file:///usr/share/ublue-os/bazaar/office.png
    banner-fit: cover
    banner-text-halign: end
    banner-text-valign: start
    banner-height: 500
    classes:
      - bazzite-section
    appids:
      - com.slack.Slack
      - md.obsidian.Obsidian
      - io.gitlab.theevilskeleton.Upscaler
      - io.github.alainm23.planify
      - org.onlyoffice.desktopeditors
      - org.libreoffice.LibreOffice
      - org.gimp.GIMP
      - org.kde.krita
      - org.inkscape.Inkscape
      - org.blender.Blender
      - com.logseq.Logseq
      - io.github.nokse22.Exhibit
      - org.audacityteam.Audacity
      - org.ardour.Ardour
      - org.gnome.Fractal
      - org.gnome.gitlab.YaLTeR.VideoTrimmer
  - title: "Games"
    subtitle: "Protocol Three: Protect the Pilot"
    rows: 3
    banner: file:///usr/share/ublue-os/bazaar/music.png
    banner-fit: cover
    banner-text-halign: start
    banner-text-valign: start
    banner-height: 500
    classes:
      - bazzite-section
    appids:
      - com.valvesoftware.Steam
      - com.heroicgameslauncher.hgl
      - com.discordapp.Discord
      - net.lutris.Lutris
      - com.vysp3r.ProtonPlus
      - com.dec05eba.gpu_screen_recorder
      - com.github.Matoking.protontricks
      - com.obsproject.Studio
      - com.feaneron.Boatswain
      - com.valvesoftware.SteamLink
      - org.gnome.Mahjongg
      - io.github.fragglet.sdl_sopwith
      - org.gnome.Sudoku
  - title: "Utilities"
    subtitle: "Stuff you didn't need until now"
    rows: 3
    banner: file:///usr/share/ublue-os/bazaar/utilities.png
    banner-fit: cover
    banner-text-halign: start
    banner-text-valign: start
    banner-height: 500
    classes:
      - bazzite-section
    appids:
      - app.drey.Warp
      - org.localsend.localsend_app
      - com.github.zocker_160.SyncThingy
      - io.github.nozwock.Packet
      - org.gnome.gitlab.somas.Apostrophe
      - org.cockpit_project.CockpitClient
      - org.gnome.gitlab.cheywood.Pulp
      - io.github.vikdevelop.SaveDesktop
      - org.gnome.World.PikaBackup
      - org.fedoraproject.MediaWriter
      - org.raspberrypi.rpi-imager
      - hu.irl.cameractrls
      - com.belmoussaoui.Decoder
      - io.gitlab.adhami3310.Converter
      - com.jeffser.Pigment
  - title: "Developers"
    subtitle: "Unleash the power of cloud native development"
    rows: 3
    banner: file:///usr/share/ublue-os/bazaar/streaming.png
    banner-fit: cover
    banner-text-halign: end
    banner-text-valign: start
    banner-height: 500
    classes:
      - bazzite-section
    appids:
      - io.podman_desktop.PodmanDesktop
      - org.gnome.Builder
      - com.getpostman.Postman
      - io.kinvolk.Headlamp
      - me.iepure.devtoolbox
      - de.leopoldluley.Clapgrep
      - sh.loft.devpod
      - io.dbeaver.DBeaverCommunity
      - cc.arduino.IDE2
      - dev.geopjr.Calligraphy
      - io.github.lo2dev.Echo
      - org.gnome.design.IconLibrary
      - io.github.ronniedroid.concessio
      - io.github.nokse22.asciidraw
  - title: "AI and Machine Learning"
    subtitle: "Experience the best of open source AI"
    rows: 1
    banner: file:///usr/share/ublue-os/bazaar/gaming.png
    banner-fit: cover
    banner-text-halign: end
    banner-text-valign: start
    banner-height: 500
    classes:
      - bazzite-section
    appids:
      - com.jeffser.Alpaca
      - io.github.qwersyk.Newelle
  - title: "Sustainability & Education"
    subtitle: "Invest in the Future"
    rows: 2
    banner: file:///usr/share/ublue-os/bazaar/office.png
    banner-fit: cover
    banner-text-halign: end
    banner-text-valign: start
    banner-height: 500
    classes:
      - bazzite-section
    appids:
      - org.endlessos.Key
      - io.github.david_swift.Flashcards
      - dev.bragefuglseth.Keypunch
      - org.tuxpaint.Tuxpaint
      - im.bernard.Memorado
      - io.github.josephmawa.Egghead
      - io.github.r_sergii.multiElement
