# SPDX-FileCopyrightText: 2023-2025 The Bluefin Project Contributors
#
# SPDX-License-Identifier: Apache-2.0

name: Anaconda LTS ISO
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-iso-lts:
    name: Build LTS ISOs
    uses: ./.github/workflows/reusable-build-iso.yml
    secrets: inherit
    with:
      image_flavors: "['main', 'gdx']"
      stream_name: lts
