name: Latest Images
on:
  merge_group:
  pull_request:
    branches:
      - main
      - testing
    paths-ignore:
      - "**.md"
  schedule:
    - cron: "40 4 * * 1,2,3,4,5,6" # 4:40 UTC All But Sunday
    - cron: "40 4 * * 0" # 4:40 UTC Sunday
  workflow_call:
  workflow_dispatch:
    inputs:
      brand_name:
        description: "Image Brand to Build"
        default: '["bluefin"]'
        type: choice
        options:
          - '["bluefin"]'
          - '["aurora"]'
          - '["bluefin", "aurora"]'

jobs:
  build-image-latest:
    name: Build Latest Images
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        brand_name: ${{ fromJson(inputs.brand_name || '["bluefin", "aurora"]') }}
    with:
      image_flavors: '["main", "nvidia", "hwe", "hwe-nvidia"]'
      brand_name: ${{ matrix.brand_name }}
      stream_name: latest

  generate-release:
    name: Generate Release
    needs: [build-image-latest]
    secrets: inherit
    uses: ./.github/workflows/generate-release.yml
    with:
      stream_name: '["latest"]'

  build-iso-latest:
    name: Build Latest ISOs
    needs: [build-image-latest]
    if: github.event.schedule == '40 4 * * 0'
    
    secrets: inherit
    uses: ./.github/workflows/build-iso-latest.yml
