name: Beta Images
on:
  merge_group: # Make Beta Images run on merge groups
  pull_request:
    branches:
      - main
      - testing
    paths-ignore:
      - "**.md"
      - ".github/workflows/*validate*.yml"
      - "system_files/shared/etc/bazaar/**"
  schedule:
    - cron: "50 5 * * 0" # 5:50 UTC sunday
  workflow_call:
  workflow_dispatch:

jobs:
  build-image-beta:
    name: Build Beta Images
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        brand_name: ["bluefin"]
    with:
      brand_name: ${{ matrix.brand_name }}
      stream_name: beta

  generate-release:
    name: Generate Release
    needs: [build-image-beta]
    secrets: inherit
    uses: ./.github/workflows/generate-release.yml
    with:
      stream_name: '["beta"]'
