name: GTS Images
on:
  pull_request:
    branches:
      - main
      - testing
    paths-ignore:
      - "**.md"
      - ".github/workflows/*validate*.yml"
      - "system_files/shared/etc/bazaar/**"
  schedule:
    - cron: "0 1 * * TUE" # Every Tuesday at 1:00 AM UTC (same as bluefin-lts)
  workflow_dispatch:
  workflow_call:

jobs:
  build-image-gts:
    name: Build GTS Images
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        brand_name: [bluefin]
    with:
      kernel_pin: 6.17.12-200.fc42.x86_64 ## Pin to 6.17 for ZFS compatibility
      brand_name: ${{ matrix.brand_name }}
      stream_name: gts

  generate_release:
    name: Generate Release
    needs: [build-image-gts]
    secrets: inherit
    uses: ./.github/workflows/generate-release.yml
    with:
      stream_name: '["gts"]'
