name: GTS Images
on:
  pull_request:
    branches:
      - main
      - testing
    paths-ignore:
      - ".github/workflows/*iso*"
      - "**.md"
      - "flatpaks/**"
      - "iso_files/**"
  schedule:
    - cron: "50 5 * * 0" # 5:50 UTC Weekly on Sundays
  workflow_dispatch:
  workflow_call:

jobs:
  build-image-gts:
    name: Build GTS Images
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        brand_name: [bluefin]
    with:
      kernel_pin: 6.14.11-200.fc41.x86_64    ## This is where kernels get pinned.
      brand_name: ${{ matrix.brand_name }}
      stream_name: gts

  generate_release:
    name: Generate Release
    needs: [build-image-gts]
    secrets: inherit
    uses: ./.github/workflows/generate-release.yml
    with:
      stream_name: '["gts"]'
