name: Latest Images HWE
on:
  schedule:
    - cron: '0 2 * * 0'  # Weekly on Sunday at 2 AM UTC
  workflow_call:
  workflow_dispatch:

jobs:
  build-image-latest:
    name: Build Latest Images
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        brand_name: ["bluefin"]
    with:
      image_flavors: '["hwe", "hwe-nvidia", "hwe-nvidia-open"]'
      brand_name: ${{ matrix.brand_name }}
      stream_name: latest

  generate-release:
    name: Generate Release
    needs: [build-image-latest]
    secrets: inherit
    uses: ./.github/workflows/generate-release.yml
    with:
      stream_name: '["latest"]'
