name: aurora 39
on:
  merge_group:
  pull_request:
    branches:
      - main
      - testing
    paths-ignore:
      - '**.md'
      - 'system_files/silverblue/**'
  schedule:
    - cron: '41 16 * * *'  # 16:41 UTC everyday
  workflow_dispatch:

jobs:
  build:
    name: build
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      brand_name: aurora
      fedora_version: 39

  scan:
    # Scan can still be ran when some builds fail since only successfully built
    # images will be stored in the output
    if: (github.event_name != 'pull_request' && github.event_name != 'merge_group') && always()
    uses: ./.github/workflows/reusable-image-scan.yml
    needs: build
    secrets: inherit
    with:
      images: ${{ needs.build.outputs.images }}
