on:
  workflow_call:
    inputs:
      stream_name:
        description: "Release Tag (e.g. gts, stable)"
        type: string
        required: true
  workflow_dispatch:
    inputs:
      handwritten:
        description: "Small Changelog about changes in this build"
      stream_name:
        description: "Release Tag (e.g. gts, stable)"
        required: true
        type: choice
        options:
          - '["gts", "stable"]'
          - '["gts"]'
          - '["stable"]'

permissions:
  contents: write

name: Generate Release
jobs:
  generate-release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJson( inputs.stream_name ) }}

    steps:
      - name: Checkout last 500 commits (for <commits> to work)
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 500

      - name: Generate Release Text
        uses: hanthor/changelog-action@master
        with:
          stream: ${{ matrix.version }}
          family: bluefin
          handwritten: ${{ inputs.handwritten }}
          output-env: ./output.env

      - name: Load outputs
        id: generate-release-text
        shell: bash
        run: |
          source ./output.env
          echo "title=${TITLE}" >> $GITHUB_OUTPUT
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2
        if: contains(fromJson('["gts", "stable"]'), matrix.version) && (github.event.schedule == '0 1 * * TUE' || contains(fromJson('["workflow_dispatch", "workflow_call"]'), github.event_name))
        with:
          name: ${{ steps.generate-release-text.outputs.title }}
          tag_name: ${{ steps.generate-release-text.outputs.tag }}
          body_path: ./changelog.md
          make_latest: ${{ matrix.version == 'stable' }}
          prerelease: false
