on:
  workflow_call:
    inputs:
      stream_name:
        description: "Release Tag (e.g. gts, stable)"
        type: string
        required: true
  workflow_dispatch:
    inputs:
      handwritten:
        description: "Small Changelog about changes in this build"
      stream_name:
        description: "Release Tag (e.g. gts, stable)"
        required: true
        type: choice
        options:
          - '["gts", "stable"]'
          - '["gts"]'
          - '["stable"]'

permissions:
  contents: write

name: Generate Release
jobs:
  generate-release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJson( inputs.stream_name ) }}

    steps:
      - name: Checkout last 500 commits (for <commits> to work)
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 500

      - name: Setup Just
        uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3

      - name: Check Just Syntax
        shell: bash
        run: |
          just check

      - name: Generate Release Text
        id: generate-release-text
        shell: bash
        run: |
          just changelogs "${{ matrix.version }}" "${{ inputs.handwritten }}"
          source ./output.env
          echo "title=${TITLE}" >> $GITHUB_OUTPUT
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2
        if: contains(fromJson('["gts", "stable"]'), matrix.version) && (github.event.schedule == '0 1 * * TUE' || contains(fromJson('["workflow_dispatch", "workflow_call"]'), github.event_name))
        with:
          name: ${{ steps.generate-release-text.outputs.title }}
          tag_name: ${{ steps.generate-release-text.outputs.tag }}
          body_path: ./changelog.md
          make_latest: ${{ matrix.version == 'stable' }}
          prerelease: false
