name: Generate ISO

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    container: fedora:latest
    strategy:
      matrix:
        fedora-version: [ 38 ]
    steps:
      - uses: actions/checkout@v3
        
      - uses: ublue-os/isogenerator@main
        id: isogenerator
        with:
          image-name: bluefin-${{ matrix.fedora-version }}
          installer-repo: development
          installer-major-version: ${{ matrix.fedora-version }}
          kickstart-file-path: bluefin.ks
          
      - uses: actions/upload-artifact@v3
        with:
          name: bluefin-${{ matrix.fedora-version }}
          path: ${{ steps.isogenerator.outputs.iso-path }}
          
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bluefin-${{ matrix.fedora-version }}
        
